---
- name: Collect Cisco IOS version information
  hosts: cisco_ios
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Run show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: version_output

    - name: Extract IOS version
      set_fact:
        ios_version: >-
          {{
            version_output.stdout[0]
            | regex_search('Version ([^,]+)', '\\1')
          }}

    - name: Show version result
      debug:
        msg:
          - "Device: {{ inventory_hostname }}"
          - "IOS Version: {{ ios_version }}"
