---
- name: Collect Cisco IOS version information
  hosts: cisco_ios
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Run show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: version_output

    - name: Extract IOS version safely (bulletproof)
      set_fact:
        ios_version: >-
          {{
            (version_output.stdout[0]
             | regex_findall('Version\\s+([^,\\s]+)')
             | first)
            | default('UNKNOWN', true)
          }}

    - name: Show parsed IOS version
      debug:
        msg:
          - "Device: {{ inventory_hostname }}"
          - "IOS Version: {{ ios_version }}"
